services:
  - type: web
    name: gamesifinished
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: MONGODB_URI
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_PUBLISHABLE_KEY
        sync: false
      - key: RAWG_API_KEY
        sync: false
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: VITE_CLOUDINARY_CLOUD_NAME
        sync: false
      - key: VITE_CLOUDINARY_UPLOAD_PRESET
        sync: false
